### ISSUE TITLE
Wont finish rendering

### ISSUE THREAD

**Issue by Azuki900** [rgm89git/ntscQTplus#13]
Whenever its about to finish I get this error

Traceback (most recent call last):
  File "C:\Users\User\ntscQTplus\app\Renderer.py", line 411, in run
    ff_command.overwrite_output().run()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
2023-12-27 03:17:51.401 | ERROR    | __main__:crash_handler:28 - Uncaught exception: [WinError 2] The system cannot find the file specified
  File "C:\Users\User\ntscQTplus\app\Renderer.py", line 411, in run
    ff_command.overwrite_output().run()

  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(

  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(

  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,

  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,

**Comment by Degamisu** [comment]
Hello. I believe I have a fix for you. When you are rendering something, click the `Render as MKV` and hit render. When it starts to render, you can turn it off. This should fix it. Let me know if this works.
