### ISSUE TITLE
ntscQT+ Crashes When Adding Audio To Video

### ISSUE THREAD

**Issue by Supergub5871** [rgm89git/ntscQTplus#6]
ffmpeg version 6.0-full_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Input #0, matroska,webm, from 'C:\Users\username\Downloads\tmp_ntscqtarg2.mkv':
  Metadata:
    ENCODER         : Lavf58.76.100
  Duration: 00:00:25.16, start: 0.000000, bitrate: 55053 kb/s
  Stream #0:0: Video: ffv1 (FFV1 / 0x31564646), bgra, 862x600, 14.98 fps, 14.98 tbr, 1k tbn (default)
    Metadata:
      DURATION        : 00:00:25.159000000
Input #1, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\username\OneDrive\Desktop\Email attachments\Documents\sm64arg2.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 19529854
    compatible_brands: mp42isom
    creation_time   : 2023-06-28T15:31:03.000000Z
  Duration: 00:01:08.74, start: 0.000000, bitrate: 11707 kb/s
  Stream #1:0[0x1](eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 320 kb/s (default)
    Metadata:
      creation_time   : 2023-06-28T15:31:03.000000Z
      handler_name    : Sound Media Handler
      vendor_id       : [0][0][0][0]
  Stream #1:1[0x2](eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 1408x980 [SAR 1:1 DAR 352:245], 11382 kb/s, 29.97 fps, 29.97 tbr, 30k tbn (default)
    Metadata:
      creation_time   : 2023-06-28T15:31:03.000000Z
      handler_name    : Video Media Handler
      vendor_id       : [0][0][0][0]
      encoder         : AVC Coding
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
[mp4 @ 0000020e6dd48f80] Could not find tag for codec ffv1 in stream #0, codec not currently supported in container
[out#0/mp4 @ 0000020e6dd48e80] Could not write header (incorrect codec parameters ?): Invalid argument
[aost#0:1/aac @ 0000020e6dd55740] Error initializing output stream:
[aac @ 0000020e6dd55a40] Qavg: nan
Conversion failed!
ffmpeg version 6.0-full_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Input #0, matroska,webm, from 'C:\Users\username\Downloads\tmp_ntscqtarg2.mkv':
  Metadata:
    ENCODER         : Lavf58.76.100
  Duration: 00:00:25.16, start: 0.000000, bitrate: 55053 kb/s
  Stream #0:0: Video: ffv1 (FFV1 / 0x31564646), bgra, 862x600, 14.98 fps, 14.98 tbr, 1k tbn (default)
    Metadata:
      DURATION        : 00:00:25.159000000
[mp4 @ 0000020693e75880] Could not find tag for codec ffv1 in stream #0, codec not currently supported in container
[out#0/mp4 @ 0000020693f2ed80] Could not write header (incorrect codec parameters ?): Invalid argument
[vost#0:0/copy @ 0000020693e76600] Error initializing output stream:
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
    Last message repeated 1 times
Traceback (most recent call last):
  File "C:\Users\username\source\repos\ntscQTplus\app\Renderer.py", line 411, in run
    ff_command.overwrite_output().run()
  File "C:\Users\username\source\repos\ntscQTplus\venv\lib\site-packages\ffmpeg\_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\username\source\repos\ntscQTplus\app\Renderer.py", line 417, in run
    ff_command.overwrite_output().run()
  File "C:\Users\username\source\repos\ntscQTplus\venv\lib\site-packages\ffmpeg\_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
2023-06-28 15:07:59.443 | ERROR    | __main__:crash_handler:27 - Uncaught exception: ffmpeg error (see stderr output for detail)
NoneType: None

**Comment by rgm89git** [comment]
I will fix that in a later build.
Basically, a mispelling in the code.

Wait until a new build is done.

**Comment by Supergub5871** [comment]
gives me this now 
Traceback (most recent call last):
  File "C:\Users\erinw\source\repos\ntscQTplus\app\Renderer.py", line 417, in run
    ff_command.overwrite_output().run()
  File "C:\Users\erinw\scoop\apps\python\current\Lib\site-packages\ffmpeg\_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
2023-07-06 21:17:03.748 | ERROR    | __main__:crash_handler:27 - Uncaught exception: ffmpeg error (see stderr output for detail)
NoneType: None


can you help me get the nonetype thing fixed?

**Comment by c4artisan** [comment]
it seems to fix itself after rendering a video in lossless mkv then turning the option off (and rendering in .mp4 again)
plus the mkv option has a bug where this video i'm trying to render freezes after like 4 seconds (but the audio keeps playing) but that could be because i compiled the app myself (to try and see if the original bug was fixed by now but it isn't i guess)
